---
title: "Seminario Fuentes: Suicidios dependientes de salud mental frente a desigualdades económicas"
author: "Malena Pérez Sevilla, Fátima Ezzahra Makroudi Ouennas"
date: "2022-10-18"
output: html_document
csl: apa.csl
toc: TRUE
toc_float: TRUE
---
# INTRODUCCIÓN

En este seminario vamos a comprobar si la salud mental y los suicidios pueden estar relacionados con la desigualdad económica de la población, y poder ver si hay un patrón entre estos tres conceptos.

Primero de todo vamos a definir cuales son estos conceptos claves:

* **Salud mental:**
*«Estado de bienestar en el cual cada individuo desarrolla su potencial, puede afrontar las tensiones de la vida, puede trabajar de forma productiva y fructífera, y puede aportar algo a su comunidad».[@OMS]*
Este estado de bienestar mental muchas veces es alterado por perturvaciones, por lo que puede derivar a trastornos mentales, esto causa angustia y/o altera las capacidades funcionales de la persona.

* **Suicidio:**
*«Todo acto por el que un individuo se causa a sí mismo una lesión, o un daño, con un grado variable en la intención de morir, cualquiera sea el grado de intención letal o de conocimiento del verdadero móvil».[@OMS]*
Este acto es previamente meditado y realizado por una persona, que es totalemnte consciente de lo que realiza y el objetivo final de sus actos.

* **Desigualdad económica:**
*«Es la diferencia que existe en la distribución de bienes, ingresos y rentas dentro de un grupo, sociedad, país o entre países».[@NacionesUnidas]*
Es la circustancia en la que hay presente una diferencia, ya sea vinculada con la renta, el capital o bienestar económico entre los diferentes individuos de población en una concreta zona geográfica.
Esto es debido a que los recursos económicos no se distribuyen de manera equitativa.

# CARGA DE DATOS
```{r cargaDatos, }
library(readr)

desi <- read_delim("INPUT/DATA/Desigualdad (S80_S20) (CCAA).csv",
                   delim = ";", escape_double = FALSE, trim_ws = TRUE)
print(desi)
ina <- read_delim("INPUT/DATA/47444.csv",
                  delim = ";", escape_double = FALSE, trim_ws = TRUE)
print(ina)
sui <- read_delim("INPUT/DATA/02001bsc.csv",
                  delim = ";", escape_double = FALSE, trim_ws = TRUE,locale=locale(encoding="latin1"))
print(sui)
```